### ISSUE TITLE
Wrong number or type of arguments for overloaded function 'Opti_set_initial'.

### ISSUE THREAD

**Issue by vahid34** [antoinefalisse/predictsim_mtp#6]
Hi predictsim_mtp team,
Thank you for sharing such a nice code for predicting walking motion. I've run your code and L faced ''Wrong number or type of arguments for overloaded function 'Opti_set_initial'.''  error at this line:
opti.set_initial(a_col, gACol.to_numpy().T)
Can you help me to find what the problem is?

**Comment by antoinefalisse** [comment]
Hi @vahid34, thanks for reporting this issue. I believe this issue was solved with this recent PR #5. Could you please pull the latest master branch and try again? Thanks

**Comment by antoinefalisse** [comment]
@vahid34 is this still an issue for you?

**Comment by vahid34** [comment]
@antoinefalisse 
I used the latest master branch and there was no problem with that and I ran it successfully. Thanks for your help.

**Comment by antoinefalisse** [comment]
Great, thanks.
